name: Node.js CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: action/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
        MONGODB_URI: mongodb://mongo:27017/testing-ci
